"""Build unsigned macOS DMGs (one per language) for Kirkouski Typographic.

Dual-Finder-window UX: the bundle on the left, ReadMe PDF on the right, over a
localized background graphic. Target install location is user scope
(~/Library/Keyboard Layouts/), no admin required — that's why this replaces
the previous .pkg (which targeted system scope with admin).

On macOS: invokes dmgbuild + hdiutil verify, produces .dmg + .sha256 sidecar.
On Windows: validates inputs and writes dmgbuild settings files per language,
skips the actual DMG assembly. This lets the user iterate on design and
content from Windows before tagging a release — CI does the real build.

Usage:
    python build_dmg.py              # all languages (en, pl, ru)
    python build_dmg.py en pl        # specific languages
"""
import hashlib
import os
import shutil
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
LANGUAGES = ["en", "pl", "ru"]
DMG_VOLUME_NAME = "Kirkouski Typographic"
BUNDLE_NAME = "Kirkouski Typographic.bundle"


def _read_version():
    """Read project version from the repo-root VERSION file (single source of truth)."""
    with open(os.path.join(SCRIPT_DIR, "VERSION"), encoding="utf-8") as f:
        return f.read().strip()


VERSION = _read_version()


def _validate_inputs():
    """Fail loudly if any committed input is missing before we start.

    We check the bundle (built by build_macos_bundle.py) and the per-language
    background + ReadMe assets that live under assets/dmg/. If any are
    missing the user gets one error listing all of them, instead of trickling
    failures across three language runs.
    """
    required = [os.path.join(SCRIPT_DIR, "build", "macos", BUNDLE_NAME)]
    for lang in LANGUAGES:
        required.append(os.path.join(SCRIPT_DIR, "assets", "dmg", f"background-{lang}.png"))
        required.append(os.path.join(SCRIPT_DIR, "assets", "dmg", f"readme-{lang}.pdf"))
    missing = [p for p in required if not os.path.exists(p)]
    if missing:
        print("ERROR: missing inputs for DMG build:", file=sys.stderr)
        for p in missing:
            print(f"  {p}", file=sys.stderr)
        print(
            "Hint: run `python build.py macos` first to produce the bundle,\n"
            "and ensure assets/dmg/ contains background-<lang>.png + readme-<lang>.pdf\n"
            "for each language in en/pl/ru.",
            file=sys.stderr,
        )
        sys.exit(1)


def _stage_payload(lang):
    """Copy the bundle + language-specific ReadMe into build/dmg/<lang>/payload/.

    The ReadMe is renamed to a neutral "ReadMe.pdf" inside the DMG so the
    dmgbuild settings.py doesn't need to know the source language — makes the
    settings file identical across languages apart from the background path.

    Returns the absolute payload directory path.
    """
    payload_root = os.path.join(SCRIPT_DIR, "build", "dmg", lang, "payload")
    if os.path.isdir(payload_root):
        shutil.rmtree(payload_root)
    os.makedirs(payload_root)

    bundle_src = os.path.join(SCRIPT_DIR, "build", "macos", BUNDLE_NAME)
    bundle_dst = os.path.join(payload_root, BUNDLE_NAME)
    shutil.copytree(bundle_src, bundle_dst)

    readme_src = os.path.join(SCRIPT_DIR, "assets", "dmg", f"readme-{lang}.pdf")
    readme_dst = os.path.join(payload_root, "ReadMe.pdf")
    shutil.copy2(readme_src, readme_dst)

    return payload_root


def _write_settings(lang, payload_root):
    """Generate build/dmg/<lang>/settings.py consumed by dmgbuild on macOS.

    All paths are emitted with forward slashes so the file is valid on macOS
    even when generated on Windows. We deliberately omit the usual
    /Applications symlink (or any symlink) because Gatekeeper blocks drops
    onto alias folders in quarantined DMGs — the background graphic tells
    the user to drop the bundle on ~/Library/Keyboard Layouts/ instead.
    """
    settings_dir = os.path.join(SCRIPT_DIR, "build", "dmg", lang)
    os.makedirs(settings_dir, exist_ok=True)
    settings_path = os.path.join(settings_dir, "settings.py")

    bundle_path = os.path.join(payload_root, BUNDLE_NAME).replace("\\", "/")
    readme_path = os.path.join(payload_root, "ReadMe.pdf").replace("\\", "/")
    bg_path = os.path.join(SCRIPT_DIR, "assets", "dmg", f"background-{lang}.png").replace("\\", "/")

    content = f'''# Generated by build_dmg.py — do not edit by hand.
format = "UDZO"
# HFS+ is dmgbuild's documented default and works on every macOS version.
# APFS would require macOS 10.13+ on the *reader* side too, with no meaningful
# size gain for a small keyboard-layout bundle. Keep HFS+ for widest reach.
filesystem = "HFS+"

files = [
    {bundle_path!r},
    {readme_path!r},
]

# Deliberately empty — Gatekeeper blocks drops onto alias folders in
# quarantined DMGs, so the background graphic directs the user to drop the
# bundle on ~/Library/Keyboard Layouts/ instead of an in-DMG symlink.
symlinks = {{}}

background = {bg_path!r}

window_rect = ((200, 120), (600, 400))
icon_size = 96
text_size = 12

icon_locations = {{
    {BUNDLE_NAME!r}: (150, 200),
    "ReadMe.pdf":    (450, 200),
}}

default_view = "icon-view"
show_icon_preview = False
include_icon_view_settings = "auto"
include_list_view_settings = "auto"
show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
'''
    with open(settings_path, "w", encoding="utf-8") as f:
        f.write(content)
    return settings_path


def _build_one(lang):
    """Stage payload + write settings for a single language.

    On macOS, continues on to invoke dmgbuild. On Windows (or any non-Darwin
    host) it returns None after staging — the inputs are ready for CI to
    finish the build.
    """
    print(f"\n{'=' * 60}\n  DMG: {lang}\n{'=' * 60}")
    payload_root = _stage_payload(lang)

    # Strip xattrs on macOS before dmgbuild reads the tree (no-op on Windows).
    # Extended attributes from e.g. Finder drag-and-drop end up baked into the
    # image and surface as Gatekeeper quarantine warnings on download.
    current_platform: str = str(sys.platform)
    if current_platform == "darwin":
        subprocess.run(["xattr", "-cr", payload_root], check=False)

    settings_path = _write_settings(lang, payload_root)
    print(f"  payload:  {payload_root}")
    print(f"  settings: {settings_path}")

    if current_platform != "darwin":
        print(f"  SKIP: DMG assembly requires macOS (detected {current_platform}); inputs staged OK.")
        return None

    return _build_one_darwin(lang, settings_path)


def _build_one_darwin(lang, settings_path):
    """macOS-only half of the per-language build: dmgbuild + hdiutil + sha256."""
    dist_dir = os.path.join(SCRIPT_DIR, "dist")
    os.makedirs(dist_dir, exist_ok=True)
    dmg_path = os.path.join(
        dist_dir, f"kirkouski-typographic-v{VERSION}-macos-{lang}.dmg"
    )
    if os.path.exists(dmg_path):
        os.remove(dmg_path)

    result = subprocess.run(
        ["dmgbuild", "-s", settings_path, DMG_VOLUME_NAME, dmg_path],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"\nFAILED: dmgbuild ({lang})", file=sys.stderr)
        if result.stdout:
            print(result.stdout[-500:], file=sys.stderr)
        if result.stderr:
            print(result.stderr[-500:], file=sys.stderr)
        sys.exit(result.returncode)
    if result.stdout:
        print(result.stdout, end="")

    verify = subprocess.run(
        ["hdiutil", "verify", dmg_path],
        capture_output=True,
        text=True,
    )
    if verify.returncode != 0:
        print(f"\nFAILED: hdiutil verify ({lang})", file=sys.stderr)
        if verify.stdout:
            print(verify.stdout[-500:], file=sys.stderr)
        if verify.stderr:
            print(verify.stderr[-500:], file=sys.stderr)
        sys.exit(verify.returncode)
    if verify.stdout:
        print(verify.stdout, end="")

    # SHA256 sidecar for release integrity checks.
    sha = hashlib.sha256()
    with open(dmg_path, "rb") as f:
        while True:
            chunk = f.read(1 << 16)
            if not chunk:
                break
            sha.update(chunk)
    sha_path = dmg_path + ".sha256"
    with open(sha_path, "w", encoding="utf-8") as f:
        f.write(f"{sha.hexdigest()}  {os.path.basename(dmg_path)}\n")

    size_kb = os.path.getsize(dmg_path) // 1024
    print(f"  -> {dmg_path} ({size_kb} KB)")
    print(f"  -> {sha_path}")
    return dmg_path


def build_all(languages=None):
    """Build DMGs for the given languages (default: all of en/pl/ru)."""
    if languages is None:
        languages = LANGUAGES
    _validate_inputs()
    results = []
    for lang in languages:
        if lang not in LANGUAGES:
            print(f"Unknown language: {lang}", file=sys.stderr)
            sys.exit(1)
        results.append((lang, _build_one(lang)))

    current_platform: str = str(sys.platform)
    if current_platform == "darwin":
        print(f"\n{'=' * 60}\n  DMG BUILD COMPLETE — v{VERSION}\n{'=' * 60}")
        for lang, path in results:
            if path:
                print(f"  {lang}: {path}")
    else:
        print(f"\n{'=' * 60}\n  DMG inputs staged (not assembled — requires macOS)\n{'=' * 60}")


def main():
    args = list(sys.argv[1:])
    langs = args if args else None
    build_all(langs)


if __name__ == "__main__":
    main()
