"""Build macOS .keylayout files from full JSON layout definitions.

Reads the complete layout JSON (generated by extract_base.py) and serializes
to .keylayout XML. No external dependencies — stdlib only.

Usage:
    python build_keylayout.py                    # builds both
    python build_keylayout.py polish             # builds Polish only
    python build_keylayout.py russian            # builds Russian only

Prerequisites:
    Run extract_base.py first to generate the full JSON files from
    the original Birman keylayouts + our overlay changes.
"""
import json
import sys
import os


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

LAYOUTS = {
    "polish": "polish_typographic_full.json",
    "russian": "russian_typographic_full.json",
}

# Unique negative keyboard ids per layout. The source JSON files inherit ids
# from the upstream Birman keylayouts (-9876, -31553) which causes a silent
# collision in macOS — if the user has Birman installed, our layouts get
# dropped because macOS caches layouts by id. We override here so the JSON
# stays an unmodified mirror of the Birman base while our build owns the id
# namespace. Range chosen to be far from common third-party ids.
KEYBOARD_IDS = {
    "polish": "-19876",
    "russian": "-19877",
}


def esc_attr(text):
    """Escape XML attribute value."""
    if not text:
        return ""
    return (text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;"))


def esc_output(text):
    """Escape output value for a .keylayout attribute.

    IMPORTANT — Apple's keylayout parser does NOT honour the standard XML
    named entities `&lt;` / `&gt;` / `&amp;` / `&quot;` inside attribute
    values. Emitting them produces keys that silently don't type at all
    (verified against Birman's Typography Layout on macOS 26 — Birman uses
    numeric refs exclusively and all its keys work; we used named entities
    and `<`/`>` broke). Every escape here MUST be a numeric char ref.
    """
    if not text:
        return ""
    result = []
    for ch in text:
        cp = ord(ch)
        if 0xE000 <= cp <= 0xE07F:
            # PUA placeholder for control chars — decode back
            result.append(f"&#x{cp - 0xE000:04X};")
        elif cp < 0x20 or cp == 0x7F:
            # Control chars (including TAB, CR, LF) — encode as &#x refs
            result.append(f"&#x{cp:04X};")
        elif ch in ("&", "<", ">", '"'):
            result.append(f"&#x{cp:04X};")
        else:
            result.append(ch)
    return "".join(result)


def serialize_keylayout(data, override_id=None, override_name=None):
    """Serialize full keylayout data dict to XML 1.1 string.

    `override_id` / `override_name` let the caller bypass the values stored
    in the source JSON. Used to break the id collision with Birman and to
    keep the human-readable name in lockstep with the project version.
    """
    lines = []
    lines.append('<?xml version="1.1" encoding="UTF-8"?>')
    lines.append('<!DOCTYPE keyboard SYSTEM "file://localhost/System/Library/DTDs/KeyboardLayout.dtd">')

    keyboard_id = override_id if override_id is not None else data["keyboard_id"]
    keyboard_name = override_name if override_name is not None else data["keyboard_name"]

    attrs = (f'group="{data["keyboard_group"]}" id="{keyboard_id}"'
             f' name="{esc_attr(keyboard_name)}"'
             f' maxout="{data["keyboard_maxout"]}"')
    lines.append(f'<keyboard {attrs}>')

    # Layouts
    lines.append('\t<layouts>')
    for layout in data["layouts"]:
        lines.append(f'\t\t<layout first="{layout["first"]}" last="{layout["last"]}"'
                     f' mapSet="{layout["mapSet"]}" modifiers="{layout["modifiers"]}"/>')
    lines.append('\t</layouts>')

    # Modifier maps
    for mm_id, mm_data in data["modifier_map"].items():
        lines.append(f'\t<modifierMap id="{mm_id}" defaultIndex="{mm_data["defaultIndex"]}">')
        for select in mm_data["selects"]:
            lines.append(f'\t\t<keyMapSelect mapIndex="{select["mapIndex"]}">')
            for mod_keys in select["modifiers"]:
                lines.append(f'\t\t\t<modifier keys="{mod_keys}"/>')
            lines.append('\t\t</keyMapSelect>')
        lines.append('\t</modifierMap>')

    # Key map sets
    for kms_id in sorted(data["key_map_sets"].keys()):
        key_maps = data["key_map_sets"][kms_id]
        lines.append(f'\t<keyMapSet id="{kms_id}">')
        for idx in sorted(key_maps.keys(), key=int):
            km_data = key_maps[idx]
            attrs = f'index="{idx}"'
            if "baseMapSet" in km_data:
                attrs += f' baseMapSet="{km_data["baseMapSet"]}" baseIndex="{km_data["baseIndex"]}"'
            lines.append(f'\t\t<keyMap {attrs}>')
            for code in sorted(km_data["keys"].keys(), key=int):
                entry = km_data["keys"][code]
                if "output" in entry:
                    lines.append(f'\t\t\t<key code="{code}" output="{esc_output(entry["output"])}"/>')
                elif "action" in entry:
                    lines.append(f'\t\t\t<key code="{code}" action="{esc_attr(entry["action"])}"/>')
            lines.append('\t\t</keyMap>')
        lines.append('\t</keyMapSet>')

    # Actions
    if data["actions"]:
        lines.append('\t<actions>')
        for action_id in sorted(data["actions"].keys()):
            whens = data["actions"][action_id]
            lines.append(f'\t\t<action id="{esc_attr(action_id)}">')
            for when in whens:
                parts = []
                if "state" in when:
                    parts.append(f'state="{esc_attr(when["state"])}"')
                if "next" in when:
                    parts.append(f'next="{esc_attr(when["next"])}"')
                if "output" in when:
                    parts.append(f'output="{esc_output(when["output"])}"')
                if "through" in when:
                    parts.append(f'through="{esc_attr(when["through"])}"')
                if "multiplier" in when:
                    parts.append(f'multiplier="{esc_attr(when["multiplier"])}"')
                lines.append(f'\t\t\t<when {" ".join(parts)}/>')
            lines.append('\t\t</action>')
        lines.append('\t</actions>')

    # Terminators
    if data["terminators"]:
        lines.append('\t<terminators>')
        for term in data["terminators"]:
            lines.append(f'\t\t<when state="{esc_attr(term["state"])}"'
                         f' output="{esc_output(term["output"])}"/>')
        lines.append('\t</terminators>')

    lines.append('</keyboard>')
    return "\n".join(lines)


# Display name shown in System Settings → Keyboard → Input Sources. Kept in
# sync with the .icns filename and the KLInfo_ key in the bundle Info.plist;
# any drift here breaks discovery. The em-dash is U+2013 EN DASH (NOT a
# regular hyphen) — must match build_macos_bundle.LAYOUTS byte-for-byte.
KEYBOARD_NAMES = {
    "polish": "Polish – Kirkouski Typographic",
    "russian": "Russian – Kirkouski Typographic",
}


def validate_xml(xml: str, label: str) -> None:
    """Verify the generated keylayout is well-formed XML.

    A regex bug shipped malformed `<when state="..." next="...""/>` (stray quote)
    in v0.1/v0.2 — silently breaking every dead key on macOS. This catch keeps
    that class of bug from ever shipping again. We use ElementTree's parser
    against a sanitized version (XML 1.1 control-char refs would otherwise trip
    the strict XML 1.0 parser, but the structure is what we care about).
    """
    import re
    import xml.etree.ElementTree as ET

    sanitized = re.sub(r"&#x[0-9A-Fa-f]+;", "?", xml)
    sanitized = sanitized.replace('<?xml version="1.1"', '<?xml version="1.0"')
    try:
        ET.fromstring(sanitized)
    except ET.ParseError as e:
        print(f"FAIL: {label} is not well-formed XML: {e}", file=sys.stderr)
        sys.exit(1)


def main():
    targets = sys.argv[1:] if len(sys.argv) > 1 else list(LAYOUTS.keys())

    os.makedirs(os.path.join(SCRIPT_DIR, "dist"), exist_ok=True)

    for target in targets:
        if target not in LAYOUTS:
            print(f"Unknown target: {target}. Use: {', '.join(LAYOUTS.keys())}")
            sys.exit(1)

        json_file = os.path.join(SCRIPT_DIR, LAYOUTS[target])
        if not os.path.exists(json_file):
            print(f"ERROR: {json_file} not found. Run extract_base.py first.")
            sys.exit(1)

        print(f"Building {target}...")
        with open(json_file, encoding="utf-8") as f:
            data = json.load(f)

        xml = serialize_keylayout(
            data,
            override_id=KEYBOARD_IDS[target],
            override_name=KEYBOARD_NAMES[target],
        )
        validate_xml(xml, f"{target}.keylayout")
        out_name = os.path.splitext(LAYOUTS[target])[0].replace("_full", "")
        out_path = os.path.join(SCRIPT_DIR, "dist", f"{out_name}.keylayout")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(xml)
        print(f"  -> {out_path} (id={KEYBOARD_IDS[target]}, {xml.count(chr(10))+1} lines)")

    print("Done.")


if __name__ == "__main__":
    main()
