#!/usr/bin/env node
// Build step for the Chrome extension.
//
// Reads the Szpargalka Sans TTF from the project's dist/ folder, base64-
// encodes it into a `data:font/ttf;base64,...` URI, and writes the result
// to font-data.js alongside this script. font-data.js is declared as the
// first content script in manifest.json, so its global assignment is
// visible to content.js at inject time with no fetch and no round-trip.
//
// Run from anywhere:
//   node extensions/chrome-mv3/build-font.mjs
//
// Regenerate this file whenever dist/SzpargalkaSans-Regular.ttf changes.

import { readFileSync, writeFileSync, statSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..', '..')
const TTF_PATH = resolve(REPO_ROOT, 'dist', 'SzpargalkaSans-Regular.ttf')
const OUT_PATH = resolve(__dirname, 'font-data.js')

let ttfBytes
try {
  ttfBytes = readFileSync(TTF_PATH)
} catch (err) {
  console.error(
    `[build-font] Could not read ${TTF_PATH}\n` +
      `           Run \`python polish_liga.py --variant cyrillic --input scripts/assets/fonts/NotoSans-Regular.ttf\` first.`,
  )
  process.exit(1)
}

const base64 = ttfBytes.toString('base64')
const dataUri = `data:font/ttf;base64,${base64}`

const out =
  '// GENERATED by extensions/chrome-mv3/build-font.mjs — do not edit.\n' +
  `// Source: dist/SzpargalkaSans-Regular.ttf (${ttfBytes.length.toLocaleString()} bytes)\n` +
  '// Regenerate whenever the font changes.\n' +
  '\n' +
  'globalThis.SZPARGALKA_FONT_DATA_URI =\n  ' +
  JSON.stringify(dataUri) +
  '\n'

writeFileSync(OUT_PATH, out, 'utf8')

const outStats = statSync(OUT_PATH)
console.log(
  `[build-font] Wrote ${OUT_PATH}\n` +
    `             TTF:       ${ttfBytes.length.toLocaleString()} bytes\n` +
    `             data URI:  ${dataUri.length.toLocaleString()} chars\n` +
    `             JS file:   ${outStats.size.toLocaleString()} bytes`,
)
